In [32]:
inputs = [[1, 2, 3, 2.5],
         [4, 1, 5, 0.5],
         [1.5, 0.5, 4, 1.5]]
weights = [
            [0.2, 0.8, -0.5, 1],
            [0.6, 0.2, 0.44, -0.98],
            [1, 0.5, 1.5, 2]
          ]
biases = [2,3,4]


weights1 = [
            [0.1, -0.8, 1],
            [0.36, 0.52, -0.18],
            [.5, 0.5, 1]
          ]
biases1 = [3,4,1]


# output = [
#             inputs[0]*weights[0][0] + inputs[1]*weights[0][1] + inputs[2]*weights[0][2] +inputs[3]*weights[0][3] + biases[0],
#             inputs[0]*weights[1][0] + inputs[1]*weights[1][1] + inputs[2]*weights[1][2] +inputs[3]*weights[1][3] + biases[1],
#             inputs[0]*weights[2][0] + inputs[1]*weights[2][1] + inputs[2]*weights[2][2] +inputs[3]*weights[2][3] + biases[2]
#         ]

# Output for current Layer
layers_output = []

# for neuron_weights, neuron_bias in zip(weights,biases):
#     neuron_output = 0
#     for weight,n_input in zip(neuron_weights,inputs):
#         neuron_output += weight * n_input
#     neuron_output += neuron_bias
#     layers_output.append(neuron_output)






In [33]:
import numpy as np

layerwise_output1 = np.dot(inputs,np.array(weights).T) + biases
layerwise_output2 = np.dot(layerwise_output1,np.array(weights1).T) + biases1

In [34]:
# print(output)
# print(layers_output)
print(layerwise_output1)
print()
print(layerwise_output2)

[[ 4.8   2.87 15.5 ]
 [ 1.6   7.31 17.  ]
 [ 2.2   4.29 14.75]]

[[16.684   4.4304 20.335 ]
 [14.312   5.3172 22.455 ]
 [14.538   4.3678 18.995 ]]


In [54]:
print(np.zeros((8,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [1]:
import numpy as np 

# Seed the generator
np.random.seed(0)

# Input Data with 4 features
X = [
     [1.0, 2.0, 3.0, 4.0],
     [2.0, 5.0, 1.0, 2.0],
     [1.5, 2.7, 3.3, 0.8]
    ]


# Class Declaration for Layer
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = np.random.randn(n_inputs, n_neurons) * 0.10
        self.biases = np.zeros((1, n_neurons))
        
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

# Number of inputs for each layer is the number of features in the input
layer1 = Layer_Dense(4,60)
layer2 = Layer_Dense(60,20)
layer3 = Layer_Dense(20,8)
layer4 = Layer_Dense(8,2)

# Output of each layer is created and assigned as input to next layer
layer1.forward(X)
layer2.forward(layer1.output)
layer3.forward(layer2.output)
layer4.forward(layer3.output)

# Output of each layer is printed
print("LAYER 1:")
print(layer1.output,"\n")
print("LAYER 2:")
print(layer2.output,"\n")
print("LAYER 3:")
print(layer3.output,"\n")
print("LAYER 4:")
print(layer4.output,"\n")

LAYER 1:
[[ 0.01324324 -0.91169567 -0.23273137 -0.61261269  0.26396325 -0.8637974
  -0.80333023  0.65306588 -0.28591833  0.79089332 -0.58789512  0.43981904
   0.08597098 -0.69248589  0.14341149  0.03071687  0.45694194  0.13062628
   0.95309266  0.13251622 -1.08337896  0.281593    0.66944199  0.07114968
   1.49562194 -0.1296973  -0.04324535 -0.01481083 -0.34367499  0.18009069
   0.27845843  0.92319537  0.04398116 -0.43725104 -0.3708322  -0.20611383
   0.45631168  0.30509333  0.54613272 -0.09808128 -0.26001289  0.0289133
  -0.32533617  0.60781484 -1.26953936  0.6235305  -0.44546532 -0.44230084
   0.34068113  0.27474302 -0.00940158  0.11818952 -0.18342106  0.23506211
  -0.82916472  0.72028206  0.55287303 -1.03561377  0.09322741  0.42417418]
 [-0.01657598 -0.48467548 -0.30972541 -0.7270047   0.51781417 -0.73172103
  -0.88947351  0.39647907 -0.55497608  0.4574415   0.05779101  0.46268125
   0.64661806 -0.82351355  0.33101419 -0.24233612  0.07543443 -0.18658553
   0.37908514  0.01526296 -1.3